//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod metric_type;
pub mod recipe;
pub mod recipe_item;
pub mod recipe_item_amount;
pub mod recipe_item_type;
pub mod recipe_metric;
pub mod recipe_step;
pub mod user;
pub mod user_info;
