//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::metric_type::Entity as MetricType;
pub use super::recipe::Entity as Recipe;
pub use super::recipe_item::Entity as RecipeItem;
pub use super::recipe_item_type::Entity as RecipeItemType;
pub use super::recipe_item_volume::Entity as RecipeItemVolume;
pub use super::recipe_metric::Entity as RecipeMetric;
pub use super::user::Entity as User;
pub use super::user_info::Entity as UserInfo;
