//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe_step")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub order: i16,
    pub recipe_id: Uuid,
    pub recipe_item_id: Uuid,
    pub tittle: String,
    pub desc: Option<String>,
    pub temperature: Option<String>,
    pub power: Option<String>,
    pub duration: Option<String>,
}

impl ActiveModelBehavior for ActiveModel {}
