//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Option<Uuid>,
    pub original: Option<Uuid>,
    pub visibility: i16,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(
        self_ref,
        relation_enum = "SelfRef",
        from = "original",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub recipe: HasOne<Entity>,
    #[sea_orm(has_many)]
    pub recipe_metrics: HasMany<super::recipe_metric::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub user: HasOne<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
