//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe_item")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub user_id: Option<Uuid>,
    pub visibility: i16,
    pub recipe_item_type_id: Option<Uuid>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(has_many)]
    pub recipe_item_amounts: HasMany<super::recipe_item_amount::Entity>,
    #[sea_orm(
        belongs_to,
        from = "recipe_item_type_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub recipe_item_type: HasOne<super::recipe_item_type::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub user: HasOne<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
