//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe_item_volume")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub recipe_item_id: Uuid,
    #[sea_orm(column_type = "Float")]
    pub amunt: f32,
    pub unit: String,
    #[sea_orm(
        belongs_to,
        from = "recipe_item_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub recipe_item: HasOne<super::recipe_item::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
