//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recipe_metric")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub metric_type_id: Uuid,
    pub recipe_id: Uuid,
    pub value: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
    #[sea_orm(
        belongs_to,
        from = "metric_type_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub metric_type: HasOne<super::metric_type::Entity>,
    #[sea_orm(
        belongs_to,
        from = "recipe_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub recipe: HasOne<super::recipe::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
