//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub username: String,
    pub create_at: DateTime,
    #[sea_orm(has_many)]
    pub recipes: HasMany<super::recipe::Entity>,
    #[sea_orm(has_many)]
    pub recipe_items: HasMany<super::recipe_item::Entity>,
    #[sea_orm(has_one)]
    pub user_info: HasOne<super::user_info::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
